-- Generated by nwg-displays on 2026-08-14 at 23:21:07. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1024x768@85.0",
    position = "0x672",
    scale = 1.0
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@164.98",
    position = "1024x0",
    scale = 1.0
})
